name: Build and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore AzureTestCaseAssociatorSln.sln

    - name: Build
      run: dotnet build AzureTestCaseAssociatorSln.sln --no-restore

    - name: Test
      run: dotnet test AzureTestCaseAssociatorSln.sln --no-build

    - name: Pack
      run: dotnet pack AzureTestCaseAssociator\AzureTestCaseAssociator.csproj --output nupkgs

    - name: Publish NuGet package
      uses: actions/upload-artifact@v2
      with:
        name: NuGet package
        path: '**/*.nupkg'
